<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">SCG</span></h1>

    <p>
        (Trading - Ciement Building Material CBM)
    </p>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Test 1</h3>
            </div>
            <div class="panel-body">
                <p>
                    1.  3, 5, 9, 15, X  - Please create new function for finding X value
                </p> 
                <p>
                    Ans. X = <?= $ans1; ?>
                </p>                
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Test 2</h3>
            </div>
            <div class="panel-body">
                <p>
                    2.  (Y + 24)+(10 x 2) = 99  - Please create new function for finding Y value
                </p>
                <p>
                    Ans. Y = <?= $ans2; ?>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Test 3</h3>
            </div>
            <div class="panel-body">
                <p>
                    3.  If 1 = 5 , 2 = 25 , 3 = 325 , 4 = 4325 Then 5 = X - Please create new function for finding X value
                </p>
                <p>
                    Ans. X = <?= $ans3; ?>
                </p>
            </div>
        </div>
    </div>
</div>
